### ISSUE TITLE
S3 Compatible storage

### ISSUE THREAD

**Issue by alebeta90** [chatwoot/charts#147]
Hi,

I was following the advice from https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers to configure S3 compatible storage passing the env vars like in my helm command

``` bash
      --set chatwoot.env.ACTIVE_STORAGE_SERVICE=s3_compatible
      --set chatwoot.env.STORAGE_BUCKET_NAME="chatwoot"
      --set chatwoot.env.STORAGE_ACCESS_KEY_ID=${CF_S3_ACCESS_KEY}
      --set chatwoot.env.STORAGE_SECRET_ACCESS_KEY=${CF_S3_SECRET_KEY}
      --set chatwoot.env.STORAGE_ENDPOINT=https://myaccountid.r2.cloudflarestorage.com
      --set chatwoot.env.STORAGE_FORCE_PATH_STYLE=true
```
But when starting the pod it returns error

```
Exiting
/gems/ruby/3.3.0/gems/aws-sdk-core-3.171.1/lib/aws-sdk-core/plugins/regional_endpoint.rb:92:in `after_initialize': No region was provided. Configure the `:region` option or export
the region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
```

Is S3 compatible storage working different in the helm deployment?

Thanks for any hint on how to solve this issue.

Bests,

**Comment by sojan-official** [comment]
ref : https://dev.to/maful/how-to-use-cloudflare-r2-with-ruby-on-rails-active-storage-acl

you can try setting the region environment variable values as  'auto'
