### ISSUE TITLE
doc: Add a video demo of using chatwoot helm charts

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/charts#16]

**Comment by pranavrajs** [comment]
@vishnu-narayanan Do you need any help to get this done?

**Comment by vishnu-narayanan** [comment]
Github only supports 100 MB attachments. Please find the recording here. Use take 2 and trim at 09:05.
https://drive.google.com/drive/folders/18vpcPqg07J8LWVSLzYULCb1UVCLIpBKP

**Comment by vishnu-narayanan** [comment]
https://www.youtube.com/watch?v=o1jnYfy8CCo
