### ISSUE TITLE
Upgrade error due to immutable selectorLabels field

### ISSUE THREAD

**Issue by thundersparkf** [chatwoot/charts#29]
<img width="1440" alt="Screenshot 2021-08-17 at 12 21 28 PM" src="https://user-images.githubusercontent.com/64605024/129677614-52eee70e-8450-47d5-b3ad-61750f1593d6.png">

<img width="264" alt="Screenshot 2021-08-17 at 12 22 35 PM" src="https://user-images.githubusercontent.com/64605024/129677770-a46e7253-fd48-47e4-97c8-d4dabcd3d4ee.png">

**Comment by vishnu-narayanan** [comment]
Got it. Working on a fix.
