### ISSUE TITLE
YAML error

### ISSUE THREAD

**Issue by thundersparkf** [chatwoot/charts#35]
<img width="964" alt="Screenshot 2021-09-08 at 3 58 24 PM" src="https://user-images.githubusercontent.com/64605024/132493543-a58eda94-2f0c-4a7e-88d7-66d576d40f9c.png">

So its been a while since we've upgraded chatwoot and now that we did, after changing the values file etc according to latest template this error is popping up.

**Comment by vishnu-narayanan** [comment]
Could you share more details on the changes you made ?

**Comment by thundersparkf** [comment]
So I didn't change any of the values as such. The values.yaml file had changed a bit so I copied the postgresHost and password etc variables in the new space(under the postgresql key in values.yaml) however this broke it

From this:
<img width="430" alt="Screenshot 2021-09-08 at 11 30 54 PM" src="https://user-images.githubusercontent.com/64605024/132560882-0829e960-fe59-4827-8f14-f8828b6ceea5.png">
To this:
<img width="503" alt="Screenshot 2021-09-08 at 11 31 24 PM" src="https://user-images.githubusercontent.com/64605024/132560991-cb4a6731-bc20-46a5-bd4c-77c61f7a3c05.png">

Everything else is pretty much the same in the env key of values file
