### ISSUE TITLE
document upgrade to latest chatwoot release

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/charts#4]
How to 
- upgrade an existing cluster as newer versions of chatwoot are released

**Comment by thundersparkf** [comment]
I checked out this: 

```helm upgrade chatwoot ./ --set deployment.image.dockerHub.chatwoot.tag=vX.X.X```

## Installation:
<img width="814" alt="Screenshot 2021-07-15 at 7 58 42 PM" src="https://user-images.githubusercontent.com/64605024/125805617-1843e5c6-4f4f-4251-add5-6ff7e1b69aa2.png">

<img width="814" alt="Screenshot 2021-07-15 at 7 59 04 PM" src="https://user-images.githubusercontent.com/64605024/125805647-32109ee6-d5bb-46a4-b2cd-e48505503421.png">

## Upgrade:

<img width="814" alt="Screenshot 2021-07-15 at 7 59 44 PM" src="https://user-images.githubusercontent.com/64605024/125805759-a1d2465f-5cf0-4f1e-ac79-6fbcf91d815a.png">
<img width="814" alt="Screenshot 2021-07-15 at 8 00 09 PM" src="https://user-images.githubusercontent.com/64605024/125805780-cd19bc26-5c34-4f30-a598-fdf6b896ee02.png">
<img width="814" alt="Screenshot 2021-07-15 at 8 00 31 PM" src="https://user-images.githubusercontent.com/64605024/125805784-f4f99cf0-7fab-4b65-9501-a067defde1c3.png">


I tried checked this by installing latest version and downgrading to 1.16. On the surface it made sense as my inboxes and labels were available and the Dialogflow integration was available only in the latest version

**Comment by vishnu-narayanan** [comment]
Closing for now. Will be updating Chart README to include upgrade steps if any.
