### ISSUE TITLE
ingressClass support

### ISSUE THREAD

**Issue by maximegaillard** [chatwoot/charts#52]
### Description

With the new ingress API, we don't need to use the `kubernetes.io/ingress.class` annotation anymore. Instead the new `ingressClassName` must be specified.

Cf. https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress

**Comment by vishnu-narayanan** [comment]
Closing as this is already merged.
