### ISSUE TITLE
Chart Upgrade issues

### ISSUE THREAD

**Issue by darkpixel** [chatwoot/charts#91]
I ended up blowing away the release and starting from scratch, but there have been a handful of issues over the last few months that keep breaking the upgrade path in helm.

![Screenshot from 2022-12-21 08-02-53](https://user-images.githubusercontent.com/158380/208954668-87d8734e-c0bd-4de7-aff0-8fbb408f52eb.png)

**Comment by vishnu-narayanan** [comment]
related: https://github.com/chatwoot/charts/issues/87

**Comment by vishnu-narayanan** [comment]
@darkpixel You mentioned in https://github.com/chatwoot/chatwoot/issues/5415 that on one upgrade, ports reversed, and you had not manually fixed it. Can this issue be related to that?

**Comment by darkpixel** [comment]
Oops--I didn't realize I already created a bug for it. ;)

It's possible the manual port changes are related.

Regardless, I blew away the install and installed the helm chart fresh, manually copying values over.

I think all of this was initially triggered by changes to the chart repo several versions ago.

I think these issues are more "informational" than anything that needs to be fixed right now.  If someone's upgrading from an older chart, I think the best option is to blow it away and create a fresh install now that the chart has been "fixed".

**Comment by darkpixel** [comment]
I cleaned up the dupe bugs.

Anyways, thanks again for the great product!

**Comment by vishnu-narayanan** [comment]
@darkpixel Thank you :)
